# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
