# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicians',
            old_name='name',
            new_name='artist_name',
        ),
    ]
