# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='bands',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='show_date',
            field=models.DateField(),
        ),
    ]
