# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0003_auto_20171025_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/documents'),
        ),
    ]
